### PR TITLE
Error logging for invalid ICAO

### LINKED ISSUE #288: 🐛 Bug Report: Crash if --icao invalid
### 👟 Reproduction steps

Run the program with the icao parameter that does not exist in `airports.csv`
```bash
$ node ./app/main.js --icao XXXX
```

### 👍 Expected behavior

Nice error message: There is no airport with the ICAO: XXXX.

### 👎 Actual Behavior

```bash
(node:14512) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'iso_country' of null
    at main (C:\work\avbot-charts\app\main.js:40:44)
    at Object.<anonymous> (C:\work\avbot-charts\app\main.js:84:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

### 🎲 Node.js version

Version 16.x.x

### 💻 Operating system

Windows

### 🧱 Your Environment

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I read the Code of Conduct

### PR DESCRIPTION
**Pull request by akgupta0777**
# Description

Previously there is no error logging for invalid ICAO codes instead we get a gigantic error message. This PR adds logging for invalid ICAO codes
 

Fixes #288  

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [X] Test A
- [X] Test B

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation/readme
- [X] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/main.js [hunk 1]
```diff
@@ -33,12 +33,16 @@ async function main() {
...
+        const fsPlaybook = fs.readFileSync(`${playbooksDir}/${airport.iso_country}.json`, 'utf8');
+        playbook = JSON.parse(fsPlaybook);
+      } catch (error) {
+        logger.error(`Playbook for ${airport.iso_country} not found`, { type: 'general' });
+        logger.error(error);
+      }
+    } else {
+      logger.error(`No airport with icao code ${options.icao} found`, { type: 'general' });
     }
     if (playbook) {
```
Comment (drph4nt0m) [inline app/main.js:47]: Lines 47-49 (`if (playbook)`) should also be inside the `if (airport)` block.

**Review by drph4nt0m — CHANGES_REQUESTED** [review]

File: app/main.js (hunk 1 above)
Comment (akgupta0777) [reply app/main.js:47]: If airport is found then playbook will also be found, else playbook will be null.

Comment (akgupta0777) [reply app/main.js:47]: But that makes sense I will fix this

**Review by drph4nt0m — APPROVED** [review]
